name: Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Perform a dry run?
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  npm-publish:
    name: npm publish
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NanoForge-dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false
          registry-url: https://registry.npmjs.org/

      - name: Install actions
        id: actions
        shell: bash
        run: |
          npm install -g @nanoforge-dev/actions && echo "ACTIONS_PATH=$(npm ls -gp @nanoforge-dev/actions)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        uses: jenseng/dynamic-uses@v1
        with:
          uses: ${{ steps.actions.outputs.ACTIONS_PATH }}/dist/pnpm-install

      - name: Build dependencies
        run: pnpm run build

      - name: Release packages
        uses: jenseng/dynamic-uses@v1
        with:
          uses: ${{ steps.actions.outputs.ACTIONS_PATH }}/dist/release-packages
          with: |
            package: "@nanoforge-dev/schematics"
            exclude: ""
            dry: ${{ inputs.dry_run }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
